# Generated by Django 5.1.2 on 2024-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
