# Generated by Django 5.1.2 on 2024-11-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='goal_icons/'),
        ),
    ]
