# Generated by Django 5.1.2 on 2024-11-02 19:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='weightage',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
