# Generated by Django 5.1.2 on 2024-11-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goal_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='icon',
            field=models.ImageField(blank=True, default='goal_icons/default_goal.png', null=True, upload_to='goal_icons/'),
        ),
    ]
