# Generated by Django 5.1.2 on 2024-11-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_goal_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='icon',
            field=models.ImageField(blank=True, default='../static/images/default_goal.png', null=True, upload_to='goal_icons/'),
        ),
    ]
